docs/other/install-cvmfs-stratum1.md
It looks like these have been mangled for a long time.  This page doesn't get a lot of use.
=> Fix stratum1 KeepAlive directives

docs/compute-element/hosted-ce.md
It looks bad with so many admonitions
=> Move button out of the admonition box

docs/data/xrootd/install-standalone.md
This has been sitting on an upushed branch for a month 🤦🏽
=> Add section about throttling IO requests (SOFTWARE-5261)

docs/common/registration.md, mkdocs.yml
(SOFTWARE-4758)
We've been directing new contacts to do this anyway so we may as well unleash it
=> Add COManage contact registration to the ToC and main doc

docs/data/xrootd/xrootd-authorization.md
https://opensciencegrid.atlassian.net/browse/SOFTWARE-5355
=> xrootd voms authorization improvements

docs/common/ca.md, docs/common/registration.md, docs/common/yum.md, docs/compute-element/htcondor-ce-overview.md, docs/compute-element/install-htcondor-ce.md, docs/data/frontier-squid.md, docs/data/run-frontier-squid-container.md, docs/data/update-oasis.md, docs/other/schedd-filebeats.md, docs/security/host-certs/overview.md, docs/worker-node/install-apptainer.md, docs/worker-node/install-wn-oasis.md
SOFTWARE-5434.  Got rid of "grid" except in code blocks and host names.  Changing VO -> collaboration will be done in a separate PR.
=> De-gridify

docs/release/updating-to-osg-36.md
=> SCHEDD_CRON changes require a condor restart (SOFTWARE-5036)

docs/common/yum.md
Verified with AL9, RL9, CS9 containers
=> Add docs for enabling EL9 OS repos

.github/workflows/deploy-mkdocs.yml, .github/workflows/validate-mkdocs.yml
Fix set-output GHA deprecation warning in validate-mkdocks.yml
=> Fix GHA deprecation warnings (Software-5354)

docs/compute-element/slurm-recipes.md
Submitted from emacs. Let's hope this doesn't blow up
=> Add initial Slurm recipe (SOFTWARE-5666)

docs/common/yum.md
- Some of these may need to be corrected later, as no OSG 23 repos are currently online and the final URLs may vary slightly
=> SOFTWARE-5662: Add the tentative urls of OSG 23 repos to the yum documentation

docs/resource-sharing/os-backfill-containers.md
Also, clean up the punctuation of the list.
=> OSPOOL-101: Remove "work-in-progress" notes from ospool-ep RPM documentation

docs/data/xrootd/install-client.md, docs/data/xrootd/install-storage-element.md, docs/data/xrootd/overview.md, mkdocs.yml
The page is very outdated and requires attention from an expert before it is usable. Remove it from the ToC and warn people off.
=> Delist 'Install XRootD SE' and warn anyone who finds it

docs/submit/ap-ospool-aup.md
We should spell out the versions instead of forcing the admins to do the work and maybe get it wrong
=> Clarify supported release series and versions (OSPOOL-110)

docs/data/xrootd/install-standalone.md, docs/data/xrootd/install-storage-element.md, docs/data/xrootd/xrootd-authorization.md
=> Update XRootD Standalone and other XRootD docs to OSG 23 (SOFTWARE-5820) (take 2)

docs/release/osg-36.md, docs/release/supported_platforms.md
1.  Folks wanted to see the explicit EL9 recommendation
1.  They also wanted some indication of our plans for future OS support
=> Address supported platforms page feedback (SOFTWARE-5841)

docs/data/stashcache/run-stashcache-container.md
=> Fix validation file in cache container install doc

mkdocs.yml
TimC requested improvements / better alignment with the article title
=> Improve container table of content entries

docs/data/osdf/install-cache-rpm.md
=> Install OSDF Cache via RPM docs (SOFTWARE-6013)

docs/data/osdf/install-origin-rpm.md
The formatting made it somewhat unclear that the logging partition
size was part of "Service requirements"
=> Remove extra layer of bullets; move logging rec to a bullet item

docs/data/osdf/install-origin-rpm.md
We expect to handle this for them in the "Joining the Origin to the
Federation" section
=> Remove duplicate OSDF registration section

docs/data/osdf/install-origin-rpm.md
1.  We don't actually ask the admin to make any changes to their
system in this section
2.  We have an "Upgrading to a Pelican Origin" admonition in the
"Before Starting" section
=> Forefront the non-Pelican upgrade section

docs/worker-node/install-apptainer.md
#201 was too aggressive in removing references to el7 from the install-apptainer page.  Information regarding unprivileged apptainer is still useful, especially the pieces about disabling network namespaces and running under docker.  There are also a number of external references (and one from the same page) that are broken by removing the Enabling Unprivileged Apptainer section.  This restores the previous info while still having no references to EL 7.
=> Restore info regarding unprivileged apptainer

docs/data/osdf/install-cache-container.md, docs/data/osdf/install-cache-rpm.md, docs/data/osdf/install-origin-rpm.md
(https://github.com/PelicanPlatform/pelican/pull/2072)
=> 8444 isn't optional anymore

docs/data/osdf/install-origin-container.md
=> Use consistent language between OSDF docs for why 8444 should be open
