docs/data/xrootd/install-standalone.md
It's too easy to overlook this section when skimming the doc; also rename the section to "Configuring authentication and authorization" since the document it links to covers both.
=> Add more text to the 'configuring auth' subsection

docs/data/frontier-squid.md
Verified with Dave D that the dichotomy really shouldn't be inbound vs
outbound, at least from the perspective of the Squid host. Frontier
Squid in the OSG acts as a forward proxy for local cluster EPs so they
shouldn't be publicly accessible except to the WLCG monitoring infrastructure.
=> Clarify Squid port requirements (SOFTWARE-5262)

docs/data/stashcache/install-cache.md, docs/data/stashcache/install-origin.md, docs/data/stashcache/run-stash-origin-container.md, docs/data/stashcache/run-stashcache-container.md, docs/data/stashcache/vo-data.md
Primarily talking about certs, but also other info mostly copied from the corresponding RPM-based install docs, as well as some random fixups.
[SOFTWARE-5226: Document how to use certs in stash-origin and stash-cache containers](https://opensciencegrid.atlassian.net/browse/SOFTWARE-5226)
=> Updates for the container based cache/origin install docs

docs/data/external-oasis-repos.md
Such a removal has never been requested before, but when it does, the timing will be tricky to avoid alarms.
=> Expand description of external oasis repository removal when exported

docs/data/run-frontier-squid-container.md
Adds a tip for https://github.com/opensciencegrid/images/pull/50#issuecomment-1218384906
=> Add recommended production frontier cache size to container docs (SOFTWARE-5289)

docs/data/stashcache/install-cache.md, docs/data/stashcache/install-origin.md, docs/data/stashcache/vo-data.md
(SOFTWARE-5257)
This updates the registration docs with instructions for the new schema in https://github.com/opensciencegrid/topology/pull/2558
Haven't updated the container cache doc yet; needs #5 merged first.
Do not merge until the above topology PR is merged and deployed in production.
=> Update registration docs with info about the new DataFederations schema

docs/release/osg-36.md
Note: The first bullet was shortened for the release announcement. Otherwise, the items are the same at the release announcement.
=> Add news for 2022-09-29 release

docs/compute-element/install-htcondor-ce.md
Instead of the 'nobody' trick (this sorta works in that the JobRouter will bail on the 'nobody' user), explicitly map to a user with a UID domain that doesn't have ALLOW_WRITE
=> Add instructions for banning a collaboration (SOFTWARE-5333)

docs/resource-sharing/os-backfill-containers.md
It was noted by a new site that there wasn't any indication that Docker was a requirement
=> Add backfill container runtime requirement

docs/data/stashcache/install-origin.md, docs/data/stashcache/run-stash-origin-container.md
[SOFTWARE-3615: Document XCache 3.2.0 auth/unauth origin variables](https://opensciencegrid.atlassian.net/browse/SOFTWARE-3615)
=> Document for XCache 3.2.0+ auth/unauth origin support

docs/data/external-oasis-repos.md
The old links were out of date and no longer valid.
=> Update cvmfs doc links

docs/data/stashcache/vo-data.md
These lists were rolled up into the paragraph with the preceding line - I think it just needed a newline before each list.
=> fix list formatting (SOFTWARE-4344)

docs/data/stashcache/install-origin.md
Remove recommendion of using x509 with stashcp to test your origin.
=> Stashcp does not support x509

docs/data/stashcache/install-cache.md, docs/data/stashcache/install-origin.md
[SOFTWARE-5473](https://opensciencegrid.atlassian.net/browse/SOFTWARE-5473). I also mentioned that you could run an auth instance, unauth instance, or both, and also that you need different services on the origin for multiuser.
[SOFTWARE-5473]: https://opensciencegrid.atlassian.net/browse/SOFTWARE-5473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update cache/origin docs to refer to the new authfile service and timer

docs/resource-sharing/user-containers.md
SOFTWARE-5521
Also remove the note that says they can't run payloads in a separate image; this will let them do it.
=> Bind-mount /dev/fuse when launching osgvo-docker-pilot via singularity

mkdocs.yml
It's easy to miss otherwise if you don't know what the acronym stands for.
=> Put the word OSDF in the table of contents

docs/worker-node/install-apptainer.md, docs/worker-node/install-singularity.md
This extends the install-apptainer instructions to include the option of installing it locally using the unprivileged installation script.
=> Add option of installing apptainer using unprivileged script

docs/resource-sharing/os-backfill-containers.md
This is one of those "if you don't know why you'd want to use it, you probably shouldn't" features but there isn't really a place for reference documentation and I don't want to have it be undocumented, so here it is.
=> Document advertising additional startd attributes (SOFTWARE-5324)

docs/data/run-frontier-squid-container.md, docs/data/stashcache/run-stash-origin-container.md, docs/data/stashcache/run-stashcache-container.md, docs/resource-sharing/os-backfill-containers.md, docs/resource-sharing/user-containers.md, docs/security/tokens/using-tokens.md
At this point, I'm very comfortable pushing folks to OSG 23 images over OSG 3.6
=> Update OSG 3.6 container references to use OSG 23 (SOFTWARE-5693)

docs/submit/ap-ospool-aup.md
Let's hold off on merging this until we get the go-ahead. I'd also like the HTCSS release highlights page to emphasize the security releases in some way for bullet 3.
=> Document minimum OSPool AP HTCSS version policy (SOFTWARE-5776)

docs/data/stashcache/run-stash-origin-container.md, docs/data/stashcache/run-stashcache-container.md
These are the two places I could find to add the info on the ENABLE_SHA1 flag. The documentation for running a hosted CE is elsewhere; Frontier-Squids I assume don't use grid certs for auth; we don't have an XRootD-Standalone image; ENABLE_SHA1 doesn't work on the EP containers (because they don't run as root and you need root to run update-crypto-policy).
There are numerous non-containerized services where a blurb mentioning EL9 and update-crypto-policy might be useful, though, but that should be a separate PR (and perhaps ticket).
=> Add info on ENABLE_SHA1 flag on cache and origin containers (SOFTWARE-5809)

docs/data/frontier-squid.md
I chose not to throw this in an admonition but instead just moved it up the list and explicitly put "hardware" in the
link name for the Ctrl-F'ers out there.
=> Highlight Squid hardware recs (SOFTWARE-5842)

docs/data/frontier-squid.md
This removes a reference to the upstream installation test, because that has now been updated to be the same test.
It also removes extraneous backquotes that shouldn't have been there.
=> Clean up frontier-squid installation test

docs/other/install-cvmfs-stratum1.md
Ryan Taylor of Compute Canada says stratum 1s work fine with SELinux, so remove the advice of disabling it.
=> Remove reference to SELinux on install-cvmfs-stratum1

docs/other/configuration-with-osg-configure.md
A "Pilot" section is also sufficient in the osg-configure config; also the doc section header should match the config section name.
=> osg-configure: Fix info on Pilot sections

docs/release/updating-to-osg-24.md
=> Add note to upgrade docs about removing duplicate worker temp dir config var

docs/security/host-certs/lets-encrypt.md
Pelican doesn't use the usual /etc/grid-security/... paths, and needs the full chain, not just the cert.
=> Update Let's Encrypt docs with info about Pelican/OSDF

docs/data/stashcache/install-origin.md, mkdocs.yml
Also add some deprecation notices to the old origin doc, with links to the new doc
=> Add new OSDF origin doc to the TOC

docs/data/osdf/install-cache-rpm.md
The required version of osdf-cache will be released tomorrow, so people won't have to get it out of testing anymore.
=> Do not require osg-testing or osg-upcoming-testing for osdf-cache

docs/resource-sharing/os-backfill-containers.md
I followed the instructions found at https://osg-htc.org/docs/resource-sharing/os-backfill-containers/ and found that I had to change the permissions on my scratch space directory. This updates the instructions to indicate this.
Two things to note:
1. This is the first time I have configured an EP, so please verify the suggestion this merge requests adds is correct.
2. I did not generate the HTML from the mkdocs sources. Feel free to edit my suggestion to suit the preferences of the document maintainer.
=> Add note about scratch-space permissions

docs/resource-sharing/os-backfill-containers.md
- Mention user permissions requirements in "Before Starting"
- Carry documentation on CVMFS and Squid that were previously only mentioned in the docker section into the RPM section.
=> SOFTWARE-6083: Document ospool-ep permissions

docs/resource-sharing/os-backfill-containers.md
Since ospool-ep.cfg looks like shell syntax, someone might assume this is correct:
CVMFSEXEC_REPOS="x y"
However, ospool-ep.cfg actually gets passed to the container utility using --env-file. Thus this is correct:
CVMFSEXEC_REPOS=x y
Be more clear about this.
=> Revise instructions surrounding CVMFSEXEC_REPOS

docs/data/osdf/install-cache-container.md
Do this until we have
https://github.com/PelicanPlatform/pelican/issues/2149
We may want to consider aligning the TLS mount locations with the RPM install / default OSDF config that we ship in https://github.com/PelicanPlatform/pelican/blob/main/systemd/10-osdf-defaults.yaml#L13-L17
=> SOFTWARE-6112: fix Pelican config mount location

docs/security/host-certs/incommon.md
There are quite a few instructions that are the same regardless of the CSR generation method used, so I made install with container vs. RPM two subheadings in the unified instruction set rather than two distinct headings.
=> SOFTWARE-4867: OSG PKI Tools Container

docs/data/osdf/install-cache-container.md
It needs to match the issuer of the director's token
=> Put the "https://" back into the DiscoveryUrl

docs/data/osdf/install-cache-container.md, docs/data/osdf/install-cache-rpm.md
```
blin@blin-work:~$ pelican object get -c https://osdf-uw-cache.svc.osg-htc.org:8443 osdf:///pelicanplatform/test/hello-world.txt /tmp/test.txt
blin@blin-work:~$ cat /tmp/test.txt
If you are seeing this message, getting an object from OSDF was successful.
```
=> SOFTWARE-6112: use the new pelicanplatform namespace for validation

docs/data/osdf/install-origin-container.md, docs/data/osdf/install-origin-rpm.md
The post-joining the federation validation still needs to be fixed up but I don't have time before heading off on vacation. I think that we should probably merge the two validation sections and just note the `-c <ORIGIN HOSTNAME>:<ORIGIN PORT>` flag in a note or something.
=> SOFTWARE-6141: first pass at origin authZ validation config

docs/data/osdf/install-cache-container.md, docs/data/osdf/install-cache-rpm.md, docs/data/osdf/install-origin-container.md, docs/data/osdf/install-origin-rpm.md
This should make the instructions more consistent between services and install instructions.
=> OSDF documentation: update the debugging instructions to use 'pelican object get' and tell the admin to set 'Logging.Level' instead of 'Debug'
